// Mock data for Students Management
// TODO: Replace with actual API calls
// API Endpoints:
// - GET /api/warden/students (Fetch all students for hostel)
// - GET /api/warden/students/:id (Fetch specific student details)
// - GET /api/warden/students/:id/outpass (Fetch student outpass history)
// - GET /api/warden/students/:id/complaints (Fetch student complaints)

import {
  getWardenStudentOutpassHistoryApi,
  getWardenStudentComplaintHistoryApi,
} from "./constants/wardenApi";

export const studentsData = [
  {
    id: "STU001",
    name: "RituRanjan Kumar",
    email: "rahul.kumar@college.edu",
    phone: "+91-98765-43210",
    guardianName: "Suresh Kumar",
    guardianPhone: "+91-95432-10876",
    hostel: "Boys Hostel A",
    room: "127",
    floor: 2,
    bed: "Upper",
    allocationDate: "2025-08-15",
    disciplinaryFlag: false,
    outpassStatus: "No Outpass",
    complaintCount: 2,
    pendingComplaints: 1,
    feeStatus: "Paid",
    dueAmount: 0,
    lastPaymentDate: "2026-02-01",
  },
  {
    id: "STU002",
    name: "Priya Sharma",
    email: "priya.sharma@college.edu",
    phone: "+91-98765-43211",
    guardianName: "Rakesh Sharma",
    guardianPhone: "+91-95432-10877",
    hostel: "Girls Hostel B",
    room: "B-105",
    floor: 1,
    bed: "Lower",
    allocationDate: "2025-08-16",
    disciplinaryFlag: false,
    outpassStatus: "Approved",
    complaintCount: 0,
    pendingComplaints: 0,
    feeStatus: "Paid",
    dueAmount: 0,
    lastPaymentDate: "2026-02-05",
  },
  {
    id: "STU003",
    name: "Arun Singh",
    email: "arun.singh@college.edu",
    phone: "+91-98765-43212",
    guardianName: "Vikram Singh",
    guardianPhone: "+91-95432-10878",
    hostel: "Boys Hostel A",
    room: "A-304",
    floor: 3,
    bed: "Upper",
    allocationDate: "2025-08-17",
    disciplinaryFlag: true,
    outpassStatus: "Exited",
    complaintCount: 5,
    pendingComplaints: 2,
    feeStatus: "Due",
    dueAmount: 15000,
    lastPaymentDate: "2026-01-05",
  },
  {
    id: "STU004",
    name: "Neha Patel",
    email: "neha.patel@college.edu",
    phone: "+91-98765-43213",
    guardianName: "Rajesh Patel",
    guardianPhone: "+91-95432-10879",
    hostel: "Girls Hostel B",
    room: "B-209",
    floor: 2,
    bed: "Lower",
    allocationDate: "2025-08-18",
    disciplinaryFlag: false,
    outpassStatus: "Overdue",
    complaintCount: 1,
    pendingComplaints: 0,
    feeStatus: "Paid",
    dueAmount: 0,
    lastPaymentDate: "2026-02-10",
  },
  {
    id: "STU005",
    name: "Mehak Verma",
    email: "mehak.verma@college.edu",
    phone: "+91-98765-43214",
    guardianName: "Arvind Verma",
    guardianPhone: "+91-95432-10880",
    hostel: "Boys Hostel A",
    room: "A-102",
    floor: 1,
    bed: "Upper",
    allocationDate: "2025-08-19",
    disciplinaryFlag: false,
    outpassStatus: "No Outpass",
    complaintCount: 0,
    pendingComplaints: 0,
    feeStatus: "Due",
    dueAmount: 8500,
    lastPaymentDate: "2026-01-20",
  },
  {
    id: "STU006",
    name: "Ritvik Nair",
    email: "ritvik.nair@college.edu",
    phone: "+91-98765-43215",
    guardianName: "Anand Nair",
    guardianPhone: "+91-95432-10881",
    hostel: "Girls Hostel B",
    room: "B-312",
    floor: 3,
    bed: "Lower",
    allocationDate: "2025-08-20",
    disciplinaryFlag: false,
    outpassStatus: "Approved",
    complaintCount: 3,
    pendingComplaints: 1,
    feeStatus: "Paid",
    dueAmount: 0,
    lastPaymentDate: "2026-02-12",
  },
  {
    id: "STU007",
    name: "Ananya Patel",
    email: "ananya.patel@college.edu",
    phone: "+91-98765-43216",
    guardianName: "Vijay Patel",
    guardianPhone: "+91-95432-10882",
    hostel: "Boys Hostel A",
    room: "A-205",
    floor: 2,
    bed: "Lower",
    allocationDate: "2025-08-21",
    disciplinaryFlag: false,
    outpassStatus: "No Outpass",
    complaintCount: 0,
    pendingComplaints: 0,
    feeStatus: "Paid",
    dueAmount: 0,
    lastPaymentDate: "2026-02-08",
  },
  {
    id: "STU008",
    name: "Kabir Gill",
    email: "kabir.gill@college.edu",
    phone: "+91-98765-43217",
    guardianName: "Harpreet Gill",
    guardianPhone: "+91-95432-10883",
    hostel: "Girls Hostel B",
    room: "B-107",
    floor: 1,
    bed: "Upper",
    allocationDate: "2025-08-22",
    disciplinaryFlag: false,
    outpassStatus: "Exited",
    complaintCount: 2,
    pendingComplaints: 0,
    feeStatus: "Due",
    dueAmount: 12000,
    lastPaymentDate: "2026-01-15",
  },
];

export const getStudentStats = (students = studentsData) => {
  return {
    total: students.length,
    outside: students.filter((s) => s.outpassStatus === "Exited").length,
    overdue: students.filter((s) => s.outpassStatus === "Overdue").length,
    complaints: students.reduce((sum, s) => sum + (s.pendingComplaints || 0), 0),
    feeDue: students.filter((s) => s.feeStatus === "Due").length,
  };
};

export const getOutpassHistory = async (studentId) => {
  const payload = await getWardenStudentOutpassHistoryApi(studentId);
  const list = Array.isArray(payload?.outpasses) ? payload.outpasses : [];
  return list.map((item) => ({
    id: item.id,
    date: item.fromDate ? new Date(item.fromDate).toISOString().split("T")[0] : "",
    status: item.status || "Pending",
    returnTime: item.entryTime ? new Date(item.entryTime).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" }) : null,
    approvedBy: item.approvedBy || "",
  }));
};

export const getComplaintHistory = async (studentId) => {
  const payload = await getWardenStudentComplaintHistoryApi(studentId);
  const list = Array.isArray(payload?.complaints) ? payload.complaints : [];
  return list.map((doc) => ({
    id: doc?._id,
    issueType: doc?.issueType || "Other",
    status: String(doc?.status || "").toLowerCase() === "in-progress" ? "In Progress" : String(doc?.status || "").toLowerCase() === "resolved" ? "Resolved" : "Pending",
    createdAt: doc?.createdAt ? new Date(doc.createdAt).toISOString().split("T")[0] : "",
    resolvedAt: doc?.handledAt ? new Date(doc.handledAt).toISOString().split("T")[0] : null,
  }));
};
