export const facultyProfile = {
  name: 'Dr. Ananya Rao',
  role: 'Associate Professor',
  department: 'Computer Science',
  email: 'ananya.rao@campus.edu',
  phone: '+1 (555) 210-9988',
  office: 'Bldg C - Room 3-214',
  since: '2018',
}

export const courses = [
  {
    id: 'cs301',
    code: 'CS 301',
    title: 'Data Structures & Algorithms',
    term: 'Spring 2026',
    schedule: 'Mon/Wed - 10:00-11:30',
    room: 'C-201',
    enrolled: 42,
    credits: 4,
  },
  {
    id: 'cs356',
    code: 'CS 356',
    title: 'Database Systems',
    term: 'Spring 2026',
    schedule: 'Tue/Thu - 12:00-1:30',
    room: 'Lab 4',
    enrolled: 35,
    credits: 3,
  },
  {
    id: 'cs410',
    code: 'CS 410',
    title: 'Machine Learning Foundations',
    term: 'Spring 2026',
    schedule: 'Fri - 9:00-12:00',
    room: 'C-310',
    enrolled: 28,
    credits: 3,
  },
]

export const studentsByCourse = {
  cs301: [
    {
      id: 's001',
      name: 'Riya Kapoor',
      roll: 'CS22-014',
      fatherName: 'A. Kapoor',
      contactNo: '98XXXXXX01',
    },
    {
      id: 's002',
      name: 'Arjun Mehta',
      roll: 'CS22-021',
      fatherName: 'P. Mehta',
      contactNo: '98XXXXXX02',
    },
    {
      id: 's003',
      name: 'Sara Kim',
      roll: 'CS22-027',
      fatherName: 'M. Kim',
      contactNo: '98XXXXXX03',
    },
    {
      id: 's004',
      name: 'Vikram Shah',
      roll: 'CS22-033',
      fatherName: 'R. Shah',
      contactNo: '98XXXXXX04',
    },
    {
      id: 's005',
      name: 'Maya Singh',
      roll: 'CS22-041',
      fatherName: 'S. Singh',
      contactNo: '98XXXXXX05',
    },
    {
      id: 's006',
      name: 'Jonas Reed',
      roll: 'CS22-048',
      fatherName: 'L. Reed',
      contactNo: '98XXXXXX06',
    },
  ],
  cs356: [
    {
      id: 's101',
      name: 'Aditi Verma',
      roll: 'CS22-052',
      fatherName: 'S. Verma',
      contactNo: '98XXXXXX07',
    },
    {
      id: 's102',
      name: 'Lucas Chen',
      roll: 'CS22-057',
      fatherName: 'R. Chen',
      contactNo: '98XXXXXX08',
    },
    {
      id: 's103',
      name: 'Noah Patel',
      roll: 'CS22-063',
      fatherName: 'D. Patel',
      contactNo: '98XXXXXX09',
    },
    {
      id: 's104',
      name: 'Emily Park',
      roll: 'CS22-069',
      fatherName: 'H. Park',
      contactNo: '98XXXXXX10',
    },
    {
      id: 's105',
      name: 'Ishaan Rao',
      roll: 'CS22-075',
      fatherName: 'K. Rao',
      contactNo: '98XXXXXX11',
    },
  ],
  cs410: [
    {
      id: 's201',
      name: 'Fatima Noor',
      roll: 'CS21-112',
      fatherName: 'Z. Noor',
      contactNo: '98XXXXXX12',
    },
    {
      id: 's202',
      name: 'Karan Joshi',
      roll: 'CS21-118',
      fatherName: 'N. Joshi',
      contactNo: '98XXXXXX13',
    },
    {
      id: 's203',
      name: 'Lena Garcia',
      roll: 'CS21-121',
      fatherName: 'P. Garcia',
      contactNo: '98XXXXXX14',
    },
    {
      id: 's204',
      name: 'Harper Williams',
      roll: 'CS21-127',
      fatherName: 'J. Williams',
      contactNo: '98XXXXXX15',
    },
  ],
}
